"""update health_metrics_daily schema for Apple Health

Revision ID: 3b86f5223fdc
Revises: e7828af2e099
Create Date: 2025-11-23 23:15:37.768084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b86f5223fdc'
down_revision: Union[str, Sequence[str], None] = 'e7828af2e099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_metrics_daily', sa.Column('weight_lbs', sa.Numeric(), nullable=True))
    op.add_column('health_metrics_daily', sa.Column('distance_miles', sa.Numeric(), nullable=True))
    op.add_column('health_metrics_daily', sa.Column('workout_minutes', sa.Integer(), nullable=True))
    op.add_column('health_metrics_daily', sa.Column('exercise_minutes', sa.Integer(), nullable=True))
    op.add_column('health_metrics_daily', sa.Column('stand_minutes', sa.Integer(), nullable=True))
    op.create_unique_constraint('uix_user_metric_date', 'health_metrics_daily', ['user_id', 'metric_date'])
    op.drop_column('health_metrics_daily', 'distance_meters')
    op.drop_column('health_metrics_daily', 'weight_kg')
    op.drop_column('health_metrics_daily', 'sleep_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_metrics_daily', sa.Column('sleep_hours', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('health_metrics_daily', sa.Column('weight_kg', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('health_metrics_daily', sa.Column('distance_meters', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint('uix_user_metric_date', 'health_metrics_daily', type_='unique')
    op.drop_column('health_metrics_daily', 'stand_minutes')
    op.drop_column('health_metrics_daily', 'exercise_minutes')
    op.drop_column('health_metrics_daily', 'workout_minutes')
    op.drop_column('health_metrics_daily', 'distance_miles')
    op.drop_column('health_metrics_daily', 'weight_lbs')
    # ### end Alembic commands ###
