"""add unique constraint to nutrition_daily

Revision ID: 47136e3b5a7e
Revises: 5ba7424a6cb7
Create Date: 2025-11-23 10:05:16.224450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47136e3b5a7e'
down_revision: Union[str, Sequence[str], None] = '5ba7424a6cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_logdate', 'nutrition_daily', ['user_id', 'log_date'])
    op.drop_column('nutrition_daily', 'meal_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_daily', sa.Column('meal_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uix_user_logdate', 'nutrition_daily', type_='unique')
    # ### end Alembic commands ###
