"""add nutrition, health metrics, and workout cahce tables

Revision ID: 5ba7424a6cb7
Revises: 8aefda52088d
Create Date: 2025-11-13 19:18:40.881105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ba7424a6cb7'
down_revision: Union[str, Sequence[str], None] = '8aefda52088d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_metrics_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('active_calories', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate', sa.Numeric(), nullable=True),
    sa.Column('sleep_hours', sa.Numeric(), nullable=True),
    sa.Column('distance_meters', sa.Numeric(), nullable=True),
    sa.Column('additional_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_metrics_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.DateTime(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('calories', sa.Numeric(), nullable=True),
    sa.Column('protein_g', sa.Numeric(), nullable=True),
    sa.Column('carbs_g', sa.Numeric(), nullable=True),
    sa.Column('fats_g', sa.Numeric(), nullable=True),
    sa.Column('fiber_g', sa.Numeric(), nullable=True),
    sa.Column('meal_count', sa.Integer(), nullable=True),
    sa.Column('protein_per_kg_bodyweight', sa.Numeric(), nullable=True),
    sa.Column('calorie_surplus_deficit', sa.Integer(), nullable=True),
    sa.Column('meals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_workout_id', sa.String(length=100), nullable=False),
    sa.Column('workout_date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_sets', sa.Integer(), nullable=True),
    sa.Column('total_volume_kg', sa.Numeric(), nullable=True),
    sa.Column('exercise_count', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('muscle_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workout_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_synced', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_cache')
    op.drop_table('nutrition_daily')
    op.drop_table('health_metrics_raw')
    op.drop_table('health_metrics_daily')
    # ### end Alembic commands ###
