"""add unique constraints for deduplication

Revision ID: 6ba511fa86aa
Revises: 4238bb629b95
Create Date: 2025-11-27 09:50:05.400943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba511fa86aa'
down_revision: Union[str, Sequence[str], None] = '4238bb629b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_user_metric_type_date'), 'health_metrics_raw', type_='unique')
    op.create_unique_constraint('uix_user_metric_datetime_type', 'health_metrics_raw', ['user_id', 'source', 'metric_date', 'metric_type'])
    op.drop_constraint(op.f('uix_user_source_workout_id'), 'workout_cache', type_='unique')
    op.create_unique_constraint('uix_user_source_workout', 'workout_cache', ['user_id', 'source', 'source_workout_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_source_workout', 'workout_cache', type_='unique')
    op.create_unique_constraint(op.f('uix_user_source_workout_id'), 'workout_cache', ['user_id', 'source', 'source_workout_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uix_user_metric_datetime_type', 'health_metrics_raw', type_='unique')
    op.create_unique_constraint(op.f('uix_user_metric_type_date'), 'health_metrics_raw', ['user_id', 'metric_type', 'metric_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
