"""add bodyweight_reps to workout_cache

Revision ID: d7d70cb7029f
Revises: 6ba511fa86aa
Create Date: 2025-11-27 10:10:05.021430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d70cb7029f'
down_revision: Union[str, Sequence[str], None] = '6ba511fa86aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_cache', sa.Column('bodyweight_reps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_cache', 'bodyweight_reps')
    # ### end Alembic commands ###
