"""rename meals to raw_data and remove computed fields

Revision ID: e7828af2e099
Revises: 47136e3b5a7e
Create Date: 2025-11-23 12:08:49.196298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7828af2e099'
down_revision: Union[str, Sequence[str], None] = '47136e3b5a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_daily', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('nutrition_daily', 'meals')
    op.drop_column('nutrition_daily', 'calorie_surplus_deficit')
    op.drop_column('nutrition_daily', 'protein_per_kg_bodyweight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_daily', sa.Column('protein_per_kg_bodyweight', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('nutrition_daily', sa.Column('calorie_surplus_deficit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('nutrition_daily', sa.Column('meals', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('nutrition_daily', 'raw_data')
    # ### end Alembic commands ###
